### PR TITLE
Update arrest-11-21-2014.txt

### PR DESCRIPTION
**Pull request by jreacher**

### CODE REVIEW

**Comment by mrandrewmills** [comment]
Greetings, jreacher

**Comment by mrandrewmills** [comment]
Greetings, jreacher

Far be it for me to interfere with another man's right to earn a living. I didn't care for it when it was done to me and the data files in this repository are not an official record, so removing a few lines is not an unreasonable request. I'll merge the pull request shortly.

Some advice first, if I may? This information is public record elsewhere, and any competent background check will turn it up. One of the most damaging things you can do during the hiring process for a position with a security clearance is to lie about any past incidents. Trust me on this, more often than not it's the cover up afterwards, not the original transgression, that gets people in trouble.

**Comment by jreacher** [comment]
Good Evenings Mr. Mills,

       Thank you for your reply and consideration.  My request for this pull was not to hide or suppress the truth, but because of it's falsely and damaging information that has the power to alter a person's career path.  My current situation is being handled by my lawyer, who agrees 100% with me that the accusation being brought was inaccurate.  I completely agree with you on the subject of trying to hide the truth when it comes to background investigation. "Google" is primitive when compared to available tools out there.  My goal was not to lie, but to do my best to make available private information only available when it's properly requested and made factually and finalized.  

Again, thank you for your time and I hope that you understand the potential to make these types of information available when it's not truly said and done.

Regards,

**Comment by mrandrewmills** [comment]
> . . . to make private information only available . . . 

I feel the need to clear up a misconception.  The data files in this repository are public record, posted weekly by Fairfax County Police on their website. I have not posted anyone's private information.

**Pull request merged**
